from django.conf.urls.defaults import *

urlpatterns = patterns('mcas.encuesta.views',
    (r'^$', 'index'),
    (r'^consultar/$', 'consultar'),
    (r'^indicadores/$', 'indicadores'),
    (r'^generales/$', 'generales'),
    (r'^familia/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^conocimiento/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^actitud/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^practica/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^estado-actual/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^percepcion/(?P<vista>[-\w]+)/$', '_get_view'),
    (r'^descarga/(?P<vista>[-\w]+)/$', '_get_view'),
    #obtener organizaciones, municipios y comunidades
    (r'^ajax/organi/$', 'get_organi'),
    (r'^ajax/munis/$', 'get_munis'),
    (r'^ajax/comunies/$', 'get_comunies'),
    #urls de descargas de word, pdf para familia
     (r'^vive.xls/$', 'vivencon_xls'),
     (r'^vive.pdf/$', 'vivencon_pdf'),
     (r'^jefe.xls/$', 'familia_jefe_xls'),
     (r'^jefe.pdf/$', 'familia_jefe_pdf'),
     (r'^miembros.xls/$', 'familia_miembros_xls'),
     (r'^miembros.pdf/$', 'familia_miembros_pdf'),
     #conocimientos
     (r'^conocimiento_abuso.xls/$', 'conocimiento_abuso_xls'),
     (r'^conocimiento_lugar.xls/$', 'conocimiento_lugar_xls'),
     (r'^conocimiento_abusan_ninos.xls.xls/$', 'conocimiento_abusan_ninos_xls'),
     (r'^conocimiento_prevenir.xls/$', 'conocimiento_prevenir_xls'),
     (r'^conocimiento_leyes.xls/$', 'conocimiento_leyes_xls'),
     (r'^conocimiento_aprendio.xls/$', 'conocimiento_aprendio_xls'),
     (r'^conocimiento_informarse.xls/$', 'conocimiento_informarse_xls'),
     (r'^conocimiento_abuso.pdf/$', 'conocimiento_abuso_pdf'),
     (r'^conocimiento_lugar.pdf/$', 'conocimiento_lugar_pdf'),
     (r'^conocimiento_abusan_ninos.pdf/$', 'conocimiento_abusan_ninos_pdf'),
     (r'^conocimiento_prevenir.pdf/$', 'conocimiento_prevenir_pdf'),
     (r'^conocimiento_leyes.pdf/$', 'conocimiento_leyes_pdf'),
     (r'^conocimiento_aprendio.pdf/$', 'conocimiento_aprendio_pdf'),
     (r'^conocimiento_informarse.pdf/$', 'conocimiento_informarse_pdf'),
     #Actitud
     (r'^actitud_abuso.xls/$', 'actitud_abuso_xls'),
     (r'^actitud_piensa.xls/$', 'actitud_piensa_xls'),
     (r'^actitud_victima.xls/$', 'actitud_victimas_xls'),
     (r'^actitud_familia.xls/$', 'actitud_familia_xls'),
     (r'^actitud_escuela.xls/$', 'actitud_escuela_xls'),
     (r'^actitud_abuso.pdf/$', 'actitud_abuso_pdf'),
     (r'^actitud_piensa.pdf/$', 'actitud_piensa_pdf'),
     (r'^actitud_victima.pdf/$', 'actitud_victimas_pdf'),
     (r'^actitud_familia.pdf/$', 'actitud_familia_pdf'),
     (r'^actitud_escuela.pdf/$', 'actitud_escuela_pdf'),
     #practica
     (r'^practica_situacion.xls/$', 'practica_situacion_xls'),
     (r'^practica_prevenir.xls/$', 'practica_prevenir_xls'),
     (r'^practica_participa_prevenir.xls/$', 'practica_participa_prevenir_xls'),
     (r'^practica_como.xls/$', 'practica_como_xls'),
     (r'^practica_situacion.pdf/$', 'practica_situacion_pdf'),
     (r'^practica_prevenir.pdf/$', 'practica_prevenir_pdf'),
     (r'^practica_participa_prevenir.pdf/$', 'practica_participa_prevenir_pdf'),
     (r'^practica_como.pdf/$', 'practica_como_pdf'),
     #estado actual
     (r'^estado_problema.xls/$', 'estado_problema_xls'),
     (r'^estado_problema_pais.xls/$', 'estado_problema_pais_xls'),
     (r'^estado_atencion.xls/$', 'estado_atencion_xls'),
     (r'^estado_lugares.xls/$', 'estado_lugares_xls'),
     (r'^estado_tipo_atencion.xls/$', 'estado_tipo_atencion_xls'),
     (r'^estado_donde.xls/$', 'estado_donde_xls'),
     (r'^estado_problema.pdf/$', 'estado_problema_pdf'),
     (r'^estado_problema_pais.pdf/$', 'estado_problema_pais_pdf'),
     (r'^estado_atencion.pdf/$', 'estado_atencion_pdf'),
     (r'^estado_lugares.pdf/$', 'estado_lugares_pdf'),
     (r'^estado_tipo_atencion.pdf/$', 'estado_tipo_atencion_pdf'),
     (r'^estado_donde.pdf/$', 'estado_donde_pdf'),
     #percepcion
     (r'^percepcion_ninos.xls/$', 'percepcion_ninos_xls'),
     (r'^percepcion_familia.xls/$', 'percepcion_familia_xls'),
     (r'^percepcion_prevenir.xls/$', 'percepcion_prevenir_xls'),
     (r'^percepcion_mensajes.xls/$', 'percepcion_mensajes_xls'),
     (r'^percepcion_reducir.xls/$', 'percepcion_reducir_xls'),
     (r'^percepcion_iglesia.xls/$', 'percepcion_iglesia_xls'),
     (r'^percepcion_medios.xls/$', 'percepcion_medios_xls'),
     (r'^percepcion_estado.xls/$', 'percepcion_estado_xls'),
     (r'^percepcion_ong.xls/$', 'percepcion_ong_xls'),
     (r'^percepcion_empresa.xls/$', 'percepcion_empresa_xls'),    
     (r'^percepcion_ninos.pdf/$', 'percepcion_ninos_pdf'),
     (r'^percepcion_familia.pdf/$', 'percepcion_familia_pdf'),
     (r'^percepcion_prevenir.pdf/$', 'percepcion_prevenir_pdf'),
     (r'^percepcion_mensajes.pdf/$', 'percepcion_mensajes_pdf'),
     (r'^percepcion_reducir.pdf/$', 'percepcion_reducir_pdf'),
     (r'^percepcion_iglesia.pdf/$', 'percepcion_iglesia_pdf'),
     (r'^percepcion_medios.pdf/$', 'percepcion_medios_pdf'),
     (r'^percepcion_estado.pdf/$', 'percepcion_estado_pdf'),
     (r'^percepcion_ong.pdf/$', 'percepcion_ong_pdf'),
     (r'^percepcion_empresa.pdf/$', 'percepcion_empresa_pdf'),
)


